### ISSUE TITLE
Shell breaks with new driver version pulled in during a pip install

### ISSUE THREAD

**Issue by aurghob33** [awslabs/amazon-qldb-shell#15]
This week, the Shell has been pulling in the newest Python driver version and breaks after default pip install 
with the following error:

qldbshell --ledger test-ledger
Traceback (most recent call last):
File "/usr/local/bin/qldbshell", line 6, in <module>
from qldbshell.__main__ import main
File "/Library/Python/3.7/site-packages/qldbshell/__main__.py", line 22, in <module>
from pyqldb.driver.pooled_qldb_driver import PooledQldbDriver
ModuleNotFoundError: No module named 'pyqldb.driver.pooled_qldb_driver'

**Comment by aurghob33** [comment]
This was merged merged recently and published to pip on last Wednesday
