### ISSUE TITLE
thread 'main' panicked when executing a statement after an expired Tx

### ISSUE THREAD

**Issue by qiushenj** [awslabs/amazon-qldb-shell#79]
**Describe the bug**
This is reproducible on 2.0.0-alpha12. After an expired transaction, the next transaction will always result in below the stack trace:
```
% /Users/qiushenj/.cargo/bin/qldb --ledger vehicle-registration
qldb> begin;
qldb *> select * from Person where GovId='qiushenj';
{
 FirstName: "Raul",
 LastName: "Lewis",
 DOB: 1963-08-19,
 GovId: "qiushenj",
 GovIdType: "Driver License",
 Address: "1719 University Street, Seattle, WA, 98109"
}
qldb *> 
qldb *> select * from Person where GovId='qiushenj';
communication failure: Transaction Kwo6rYpDzh59SxfC1bz5QO has expired
qldb> begin;
qldb *> select * from Person where GovId='qiushenj';
thread 'main' panicked at 'session AT6AVnwovNkC1I215EscyKDBVVIpgtWn+2UtSBNHiAXsBkxubjU1eGmBFxsxt5sHxiOVv+Bu6jYFjTs8Yxy4U4XMF3I1URn4FdAm4/Kmw0cyx2ypIiwOUcwXa+0yUCRP9xMuy4gIkc5WxY1F+DS5TyMG1oMWGu47NBUu3BsxmZwpb6Nq+7Z+fIuusm64833vqCAx6ZjZHhYAxgeho0b8fE0cjfIYyPZdtCVU2Dk4bnZKt0uJC9NBS3JTTUqrN6QZBf+FyRm5s1rhr/7EVLqpYBqILHOCxg29RNkPC2b6IUnW9nJORXXhGZEg2ppx7ddjLwWIkm6mcloKgMaQb65ahrU= should have been discarded', /Users/qiushenj/.cargo/git/checkouts/amazon-qldb-driver-rust-6eae615729873ff4/813b93e/src/pool.rs:137:17
stack backtrace:
  0: rust_begin_unwind
       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
  1: std::panicking::begin_panic_fmt
       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:435:5
  2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  4: amazon_qldb_shell::transaction::new_transaction::{{closure}}::{{closure}}::{{closure}}
  5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  6: tokio::runtime::task::harness::poll_future
  7: tokio::runtime::task::harness::Harness<T,S>::poll
  8: std::thread::local::LocalKey<T>::with
  9: tokio::macros::scoped_tls::ScopedKey<T>::set
 10: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
 11: tokio::runtime::Runtime::block_on
 12: qldb::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
{
 FirstName: "Raul",
 LastName: "Lewis",
 DOB: 1963-08-19,
 GovId: "qiushenj",
 GovIdType: "Driver License",
 Address: "1719 University Street, Seattle, WA, 98109"
}
qldb *>
```

**To Reproduce**
1. Start QLDB Rust Shell as usual
2. Start a transaction
3. Execute a statement which is successful.
4. Wait for 30s.
5. Execute another statement which will result with "Transaction xxx has expired" error.
6. Start a new transaction
7. Execute a statement.
8. You'll see above stack trace first, then followed by the expected output from the executed statement.

**Expected behavior**
In step #8 above, only see the output from the executed statement.

**Screenshots**
NQ

**Desktop (please complete the following information):**
 - OS: Mac

**Additional context**
cargo built directly from the source code on version 2.0.0-alpha12.

**Comment by marcbowes** [comment]
Thanks for the report. I can reproduce it locally.

**Comment by marcbowes** [comment]
I added some tracing:

```
modified   src/pool.rs
@@ -9,7 +9,7 @@ use async_trait::async_trait;
 use bb8::{ErrorSink, ManageConnection};
 use rusoto_core::RusotoError;
 use rusoto_qldb_session::*;
-use tracing::debug;
+use tracing::{debug, error};
 
 pub struct QldbSessionManager<C>
 where
@@ -78,7 +78,10 @@ where
 
     pub(crate) fn notify_invalid(&self) {
         if let Ok(mut g) = self.inner.lock() {
+            debug!(session = %g.token, "session will be marked as invalid");
             g.discard = true;
+        } else {
+            error!("unable to mark session as invalid, this likely a bug");
         }
     }
 }
@@ -149,6 +152,10 @@ where
         let is_start_session = input.start_session.is_some();
         let res = client.send_command(input).await;
 
+        if let Err(ref e) = res {
+            debug!(error = %e, "api error");
+        }
+
         if let Err(RusotoError::Service(SendCommandError::InvalidSession(_))) = res {
             self.notify_invalid();
         }
```

Then ran the repro (some artistic edits, mine :)).

```
[2021-05-22T05:45:41.125566+00:00] DEBUG: qldb/47924 on me: api error (target=amazon_qldb_driver::pool, line=156, error="Transaction THE_TRANSACTION_ID has expired")
    file: $me/code/amazon-qldb-driver-rust/src/pool.rs
[2021-05-22T05:45:41.125676+00:00] DEBUG: qldb/47924 on me: session will be marked as invalid (target=amazon_qldb_driver::pool, line=81)
    file: $me/code/amazon-qldb-driver-rust/src/pool.rs
    --
    session: THE_SESSION_THAT_IS_BROKEN
```

That seems like a bug - why is the session being marked invalid? Just because the transaction has expired doesn't mean the session should be discarded.

The driver then aborted the transaction which seems to be not necessary (since the server just told us the transaction has expired).

At this point, the session has *not* been handled back to the pool and thus this code triggers the panic:

```
    async fn send_command(
        &self,
        input: SendCommandRequest,
    ) -> Result<SendCommandResult, RusotoError<SendCommandError>> {
        let client = if let Ok(g) = self.inner.lock() {
            if g.discard {
                panic!("session {} should have been discarded", g.token)
            }
```

It's not super clear to me why the *next* transaction lands up being the thing that drives the coroutine for the previous transaction. I think the panic lands up killing one of the tokio threads, it's also not clear to me what happens next (do you lose a thread forever? does it come back clean?).

**Comment by marcbowes** [comment]
Some more detail..

(1) This is code in the shell - specifically, the coroutine that is running a transaction lambda:

```rust
Some(TransactionRequest::ExecuteStatement(partiql)) => {
    let results = tx.execute_statement(partiql).await; // <----- Look here!
    if let Err(_) = output.send(results).await {
        panic!("results ch should never be closed");
    }
}
```

Notice that it sends the results verbatim into `output`. i.e. it's not `let results = ... .await?`. In this way, the output ch gets an Err (bad request - tx has expired).

(2) This is the code that receives the Err:

```rust
let results = match tx.results.recv().await {
    Some(Ok(r)) => r,
    Some(Err(e)) => {
        // Some errors end the transaction, some are recoverable.
        if let QldbError::Rusoto(rusoto_core::RusotoError::Service(ref service)) = e {
            let broken = match service {
                rusoto_qldb_session::SendCommandError::BadRequest(_) // <----- Look here!
                    | rusoto_qldb_session::SendCommandError::InvalidSession(_) => true,
                _ => false,
            };
            if broken {
                let _ = self.current_transaction.take(); // <----- Look here!
            }
```

It receives the "bad request" and determines this transaction might be doomed. Then it drops the coroutine.

(3) Finally, this code in the coroutine lands up calling abort:

```rust

match input.await {
    /* elided */
    Some(TransactionRequest::Abort) | None => {
        break tx.abort().await;
    }
```

**Comment by marcbowes** [comment]
@qiushenj if you're able to, please verify that the above commit fixed the issue (it did for me).

**Comment by qiushenj** [comment]
I built the shell with above commit and verified that the issue has been fixed.
